
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));
        setLocationRelativeTo(null);
        
        btnEqual.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtNumb1 = new javax.swing.JTextField();
        txtNumb2 = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        txtOperation = new javax.swing.JTextField();
        txtRemainder = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tglYear1 = new javax.swing.JToggleButton();
        tglYear2 = new javax.swing.JToggleButton();
        lblYear = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        lblYearDesc = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtNumb1.setEditable(false);
        txtNumb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNumb1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumb1.setBorder(null);
        txtNumb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumb1ActionPerformed(evt);
            }
        });

        txtNumb2.setEditable(false);
        txtNumb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNumb2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumb2.setBorder(null);

        txtResult.setEditable(false);
        txtResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResult.setBorder(null);

        txtOperation.setEditable(false);
        txtOperation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOperation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOperation.setBorder(null);

        txtRemainder.setEditable(false);
        txtRemainder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtRemainder.setForeground(new java.awt.Color(255, 0, 0));
        txtRemainder.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRemainder)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtResult)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumb2)
                            .addComponent(txtNumb1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumb2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRemainder)
                    .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMultiply.setText("x");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnDivide.setText("÷");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tglYear1.setText("Year 1");
        tglYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglYear1ActionPerformed(evt);
            }
        });

        tglYear2.setText("Year 2");
        tglYear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglYear2ActionPerformed(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblYear.setForeground(new java.awt.Color(255, 0, 0));
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHistory.setText("History");
        btnHistory.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0))));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        lblYearDesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblYearDesc.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglYear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tglYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(lblYearDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblYearDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tglYear1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglYear2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int add(int num1, int num2){
        return num1 + num2;
    }
    
    public static int subtract(int num1, int num2){
        return num1 - num2;
    }
    
    public static int multiply(int num1, int num2){
        return num1 * num2;
    }
    
    public static int divide(int num1, int num2){
        return num1 / num2;
    }
    
    public void getYearOne(int Numb1, int Numb2, String Operator, ActionEvent evt){
        int result=0;
        if(Operator.equals("+")){
            result = add(Numb1,Numb2);
            CalculatorDB.insert(Numb1,Numb2,result,Operator);
        }
        else if(Operator.equals("-")){
            if(Numb1 >= Numb2){
                result = subtract(Numb1,Numb2);
                CalculatorDB.insert(Numb1,Numb2,result,Operator);
            }
            else{
                JOptionPane.showMessageDialog(null, "First number must be bigger than second number !");
                btnClearActionPerformed(evt);
            }
        }
        txtResult.setText(String.valueOf(result));
        
    }
    
    public void getYearTwo(int Numb1, int Numb2, String Operator, ActionEvent evt){
        int result=0;
        if(Operator.equals("+")){
            result = add(Numb1,Numb2);
            CalculatorDB.insert(Numb1,Numb2,result,Operator);
        }
        else if(Operator.equals("-")){
            if(Numb1 >= Numb2){
                result = subtract(Numb1,Numb2);
                CalculatorDB.insert(Numb1,Numb2,result,Operator);
            }
            else{
                JOptionPane.showMessageDialog(null, "First number must be bigger than second number !");
                btnClearActionPerformed(evt);
            }
        }
        else if(Operator.equals("x")){
            result = multiply(Numb1,Numb2);
            CalculatorDB.insert(Numb1,Numb2,result,Operator);
        }
        else if(Operator.equals("÷")){
            int remainder = Numb1 % Numb2;
            result = divide(Numb1,Numb2);
            CalculatorDB.insert(Numb1,Numb2,result,Operator);
            
            txtRemainder.setText("Remainder : " + remainder);
        }
        txtResult.setText(String.valueOf(result));
        
        
    }
    
    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        int numb1,numb2,result=0;
        String operator;
        
        operator = txtOperation.getText();
        numb1 = Integer.parseInt(txtNumb1.getText());
        numb2 = Integer.parseInt(txtNumb2.getText());
        
        if(tglYear1.isSelected() && numb1 <= 100 && numb2 <= 100){
            getYearOne(numb1,numb2,operator,evt);
        }
        else if(tglYear2.isSelected() && numb1 <= 1000 && numb2 <= 1000){
            getYearTwo(numb1,numb2,operator,evt);
        }
        else{
            JOptionPane.showMessageDialog(null, "The number inserted is too big!");
            btnClearActionPerformed(evt);      
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "1");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "1");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "1");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "1");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "2");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "2");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "2");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "2");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "3");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "3");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "3");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "3");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "4");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "4");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "4");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "4");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "5");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "5");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "5");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "5");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "6");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "6");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "6");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "6");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "7");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "7");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "7");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "7");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "8");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "8");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "8");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "8");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "9");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "9");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "9");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "9");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 3){
                txtNumb1.setText(txtNumb1.getText() + "0");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 3){
                txtNumb2.setText(txtNumb2.getText() + "0");
            }
        }
        else if(tglYear2.isSelected()){
            if(txtOperation.getText().isEmpty() && txtNumb1.getText().length() < 4){
                txtNumb1.setText(txtNumb1.getText() + "0");
            }
            else if(!txtOperation.getText().isEmpty() && txtNumb2.getText().length() < 4){
                txtNumb2.setText(txtNumb2.getText() + "0");
            }
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        txtOperation.setText("+");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        txtOperation.setText("-");
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        txtOperation.setText("x");
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        txtOperation.setText("÷");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void txtNumb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumb1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtNumb1.setText("");
        txtNumb2.setText("");
        txtOperation.setText("");
        txtResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        int length1 = txtNumb1.getText().length();
        int length2 = txtNumb2.getText().length();
        int number1 = txtNumb1.getText().length()-1;
        int number2 = txtNumb2.getText().length()-1;
        String store;
        
        if(!txtOperation.getText().isEmpty()){
            if(length2 > 0){
                StringBuilder back2 = new StringBuilder(txtNumb2.getText());
                back2.deleteCharAt(number2);
                store = back2.toString();
                txtNumb2.setText(store);
            }
            else{
                txtOperation.setText("");
            }
        }
        else if(txtOperation.getText().isEmpty()){
            if(length1 > 0){
                StringBuilder back1 = new StringBuilder(txtNumb1.getText());
                back1.deleteCharAt(number1);
                store = back1.toString();
                txtNumb1.setText(store);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "The number is exceeded the maximum.");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void tglYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglYear1ActionPerformed
        // TODO add your handling code here:
        if(tglYear1.isSelected()){
            tglYear2.setSelected(false);
            lblYear.setText("Year 1");
            lblYearDesc.setText("Year 1 : Enter number less than 100");
            
            btnEqual.setEnabled(true);
            btnMultiply.setEnabled(false);
            btnDivide.setEnabled(false);
            
            
            btnClearActionPerformed(evt);
            
        }
        else{
            lblYear.setText("");
            lblYearDesc.setText("");
            btnEqual.setEnabled(false);
        }
    }//GEN-LAST:event_tglYear1ActionPerformed

    private void tglYear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglYear2ActionPerformed
        // TODO add your handling code here:
        if(tglYear2.isSelected()){
            tglYear1.setSelected(false);
            lblYear.setText("Year 2");
            lblYearDesc.setText("Year 2 : Enter number less than 1000");
            
            btnEqual.setEnabled(true);
            btnMultiply.setEnabled(true);
            btnDivide.setEnabled(true);
            
            btnClearActionPerformed(evt);
        }
        else{
            lblYear.setText("");
            lblYearDesc.setText("");
            btnEqual.setEnabled(false);
            
        }
    }//GEN-LAST:event_tglYear2ActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        CalculatorHistory.main(new String[]{});
    }//GEN-LAST:event_btnHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYearDesc;
    private javax.swing.JToggleButton tglYear1;
    private javax.swing.JToggleButton tglYear2;
    private javax.swing.JTextField txtNumb1;
    private javax.swing.JTextField txtNumb2;
    private javax.swing.JTextField txtOperation;
    private javax.swing.JTextField txtRemainder;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
